# ==========================================================
# 测试环境配置
# ==========================================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intensifiedmycode_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
  flyway:
    # 测试环境允许 clean
    clean-disabled: false

logging:
  level:
    com.example: INFO
